package com.dermawise.backend.rules

import com.dermawise.backend.SkincareRequest
import com.dermawise.backend.SkincareResult
import com.dermawise.backend.Budzet
import com.dermawise.backend.Sastojak

rule "Akne - ekonomičan budžet (jutarnja rutina, vec korisceni niacinamidi)"
salience 79
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.EKONOMICAN, korisceniSastojci contains Sastojak.NIACINAMID)
    rezultat: SkincareResult(kategorijaNege contains "Akne", jutarnjaRutina.aktivneSupstance excludes "Niacinamid")
then
	rezultat.getJutarnjaRutina().dodajSerum("Revox B77 Just Niacinamide 10%, 30 ml");
	rezultat.getJutarnjaRutina().dodajAktivnuSupstancu("Niacinamid");
	update(rezultat);
end

rule "Akne - ekonomičan budžet (jutarnja rutina, nisu korisceni niacinamidi)"
salience 79
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.EKONOMICAN, korisceniSastojci excludes Sastojak.NIACINAMID)
    rezultat: SkincareResult(kategorijaNege contains "Akne", jutarnjaRutina.aktivneSupstance excludes "Niacinamid")
then
	rezultat.getJutarnjaRutina().dodajSerum("Balea Anti-Pickel Serum, 30 ml");
	rezultat.getJutarnjaRutina().dodajAktivnuSupstancu("Niacinamid");
	update(rezultat);
end

rule "Akne - ekonomičan budžet (vecernja rutina, vec koriscena salicilna kiselina)"
salience 79
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.EKONOMICAN, korisceniSastojci contains Sastojak.SALICILNA_KISELINA)
    rezultat: SkincareResult(kategorijaNege contains "Akne", vecernjaRutina.aktivneSupstance excludes "Salicilna kiselina")
then
	rezultat.getVecernjaRutina().dodajSerum("Revox B77 Just Salicylic Acid 2%, 30 ml");
	rezultat.getVecernjaRutina().dodajAktivnuSupstancu("Salicilna kiselina");
	update(rezultat);
end

rule "Akne - ekonomičan budžet (vecernja rutina, nije koriscena salicilna kiselina)"
salience 79
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.EKONOMICAN, korisceniSastojci excludes Sastojak.SALICILNA_KISELINA)
    rezultat: SkincareResult(kategorijaNege contains "Akne", vecernjaRutina.aktivneSupstance excludes "Salicilna kiselina")
then
	rezultat.getVecernjaRutina().dodajSerum("Balea Beauty Expert Clarifying Toner sa 0.8% - 1% BHA, 30 ml");
	rezultat.getVecernjaRutina().dodajAktivnuSupstancu("Salicilna kiselina");
	update(rezultat);
end

rule "Akne - srednji budžet (jutarnja rutina, vec korisceni niacinamidi)"
salience 79
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.SREDNJI, korisceniSastojci contains Sastojak.NIACINAMID)
    rezultat: SkincareResult(kategorijaNege contains "Akne", jutarnjaRutina.aktivneSupstance excludes "Niacinamid")
then
	rezultat.getJutarnjaRutina().dodajSerum("Vichy Liftactiv B3 Serum, 30 ml");
	rezultat.getJutarnjaRutina().dodajAktivnuSupstancu("Niacinamid");
	update(rezultat);
end

rule "Akne - srednji budžet (jutarnja rutina, nisu korisceni niacinamidi)"
salience 79
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.SREDNJI, korisceniSastojci excludes Sastojak.NIACINAMID)
    rezultat: SkincareResult(kategorijaNege contains "Akne", jutarnjaRutina.aktivneSupstance excludes "Niacinamid")
then
	rezultat.getJutarnjaRutina().dodajSerum("The Ordinary Niacinamide 5% Emulsion, 100 ml");
	rezultat.getJutarnjaRutina().dodajAktivnuSupstancu("Niacinamid");
	update(rezultat);
end

rule "Akne - srednji budžet (vecernja rutina, vec koriscena salicilna kiselina)"
salience 79
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.SREDNJI, korisceniSastojci contains Sastojak.SALICILNA_KISELINA)
    rezultat: SkincareResult(kategorijaNege contains "Akne", vecernjaRutina.aktivneSupstance excludes "Salicilna kiselina")
then
	rezultat.getVecernjaRutina().dodajSerum("Geek & Gorgeous Porefectly Clear, 30 ml");
	rezultat.getVecernjaRutina().dodajAktivnuSupstancu("Salicilna kiselina");
	update(rezultat);
end

rule "Akne - srednji budžet (vecernja rutina, nije koriscena salicilna kiselina)"
salience 79
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.SREDNJI, korisceniSastojci excludes Sastojak.SALICILNA_KISELINA)
    rezultat: SkincareResult(kategorijaNege contains "Akne", vecernjaRutina.aktivneSupstance excludes "Salicilna kiselina")
then
	rezultat.getVecernjaRutina().dodajSerum("Paula's Choice Clear 1% BHA Exfoliant, 100 ml");
	rezultat.getVecernjaRutina().dodajAktivnuSupstancu("Salicilna kiselina");
	update(rezultat);
end

rule "Akne - premium budžet (jutarnja rutina, vec korisceni niacinamidi)"
salience 79
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.PREMIUM, korisceniSastojci contains Sastojak.NIACINAMID)
    rezultat: SkincareResult(kategorijaNege contains "Akne", jutarnjaRutina.aktivneSupstance excludes "Niacinamid")
then
	rezultat.getJutarnjaRutina().dodajSerum("Paula's Choice 10% Niacinamide Booster, 20 ml");
	rezultat.getJutarnjaRutina().dodajAktivnuSupstancu("Niacinamid");
	update(rezultat);
end

rule "Akne - premium budžet (jutarnja rutina, nisu korisceni niacinamidi)"
salience 79
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.PREMIUM, korisceniSastojci excludes Sastojak.NIACINAMID)
    rezultat: SkincareResult(kategorijaNege contains "Akne", jutarnjaRutina.aktivneSupstance excludes "Niacinamid")
then
	rezultat.getJutarnjaRutina().dodajSerum("Paula's Choice Calm Repairing Serum, 30 ml");
	rezultat.getJutarnjaRutina().dodajAktivnuSupstancu("Niacinamid");
	update(rezultat);
end

rule "Akne - premium budžet (vecernja rutina, vec koriscena salicilna kiselina)"
salience 79
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.PREMIUM, korisceniSastojci contains Sastojak.SALICILNA_KISELINA)
    rezultat: SkincareResult(kategorijaNege contains "Akne", vecernjaRutina.aktivneSupstance excludes "Salicilna kiselina")
then
	rezultat.getVecernjaRutina().dodajSerum("Paula's Choice 2% BHA Liquid Exfoliant, 118 ml");
	rezultat.getVecernjaRutina().dodajAktivnuSupstancu("Salicilna kiselina");
	update(rezultat);
end

rule "Akne - premium budžet (vecernja rutina, nije koriscena salicilna kiselina)"
salience 79
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.PREMIUM, korisceniSastojci excludes Sastojak.SALICILNA_KISELINA)
    rezultat: SkincareResult(kategorijaNege contains "Akne", vecernjaRutina.aktivneSupstance excludes "Salicilna kiselina")
then
	rezultat.getVecernjaRutina().dodajSerum("Paula's Choice Calm 1% BHA Exfoliant, 118 ml");
	rezultat.getVecernjaRutina().dodajAktivnuSupstancu("Salicilna kiselina");
	update(rezultat);
end

rule "Bore - ekonomičan budžet (jutarnja rutina, vec koriscen vitamin c)"
salience 82
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.EKONOMICAN, korisceniSastojci contains Sastojak.VITAMIN_C)
    rezultat: SkincareResult(kategorijaNege contains "AntiAge", jutarnjaRutina.aktivneSupstance excludes "Vitamin C")
then
	rezultat.getJutarnjaRutina().dodajSerum("Revox B77 Just Vitamin C 20%, 30 ml");
	rezultat.getJutarnjaRutina().dodajAktivnuSupstancu("Vitamin C");
	update(rezultat);
end

rule "Bore - ekonomičan budžet (jutarnja rutina, nije koriscen vitamin c)"
salience 82
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.EKONOMICAN, korisceniSastojci excludes Sastojak.VITAMIN_C)
    rezultat: SkincareResult(kategorijaNege contains "AntiAge", jutarnjaRutina.aktivneSupstance excludes "Vitamin C")
then
	rezultat.getJutarnjaRutina().dodajSerum("Balea VITAMIN C serum za lice, 30 ml");
	rezultat.getJutarnjaRutina().dodajAktivnuSupstancu("Vitamin C");
	update(rezultat);
end

rule "Bore - ekonomičan budžet (vecernja rutina, vec koriscen retinol)"
salience 82
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.EKONOMICAN, korisceniSastojci contains Sastojak.RETINOL)
    rezultat: SkincareResult(kategorijaNege contains "AntiAge", vecernjaRutina.aktivneSupstance excludes "Retinol")
then
	rezultat.getVecernjaRutina().dodajSerum("Revox B77 Serum za lice - RETINOL, 30 ml");
	rezultat.getVecernjaRutina().dodajAktivnuSupstancu("Retinol");
	update(rezultat);
end

rule "Bore - ekonomičan budžet (vecernja rutina, nije koriscen retinol)"
salience 82
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.EKONOMICAN, korisceniSastojci excludes Sastojak.RETINOL)
    rezultat: SkincareResult(kategorijaNege contains "AntiAge", vecernjaRutina.aktivneSupstance excludes "Retinol")
then
	rezultat.getVecernjaRutina().dodajSerum("Balea Beauty Collagen Retinol serum za lice, 30 ml");
	rezultat.getVecernjaRutina().dodajAktivnuSupstancu("Retinol");
	update(rezultat);
end

rule "Bore - srednji budžet (jutarnja rutina, vec koriscen vitamin c)"
salience 82
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.SREDNJI, korisceniSastojci contains Sastojak.VITAMIN_C)
    rezultat: SkincareResult(kategorijaNege contains "AntiAge", jutarnjaRutina.aktivneSupstance excludes "Vitamin C")
then
	rezultat.getJutarnjaRutina().dodajSerum("Geek & Gorgeous C-Glow, 30 ml");
	rezultat.getJutarnjaRutina().dodajAktivnuSupstancu("Vitamin C");
	update(rezultat);
end

rule "Bore - srednji budžet (jutarnja rutina, nije koriscen vitamin c)"
salience 82
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.SREDNJI, korisceniSastojci excludes Sastojak.VITAMIN_C)
    rezultat: SkincareResult(kategorijaNege contains "AntiAge", jutarnjaRutina.aktivneSupstance excludes "Vitamin C")
then
	rezultat.getJutarnjaRutina().dodajSerum("Q+A Vitamin C Brightening Serum, 30 ml");
	rezultat.getJutarnjaRutina().dodajAktivnuSupstancu("Vitamin C");
	update(rezultat);
end

rule "Bore - srednji budžet (vecernja rutina, vec koriscen retinol)"
salience 82
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.SREDNJI, korisceniSastojci contains Sastojak.RETINOL)
    rezultat: SkincareResult(kategorijaNege contains "AntiAge", vecernjaRutina.aktivneSupstance excludes "Retinol")
then
	rezultat.getVecernjaRutina().dodajSerum("Geek & Gorgeous A-Game 0.1, 30 ml");
	rezultat.getVecernjaRutina().dodajAktivnuSupstancu("Retinol");
	update(rezultat);
end

rule "Bore - srednji budžet (vecernja rutina, nije koriscen retinol)"
salience 82
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.SREDNJI, korisceniSastojci excludes Sastojak.RETINOL)
    rezultat: SkincareResult(kategorijaNege contains "AntiAge", vecernjaRutina.aktivneSupstance excludes "Retinol")
then
	rezultat.getVecernjaRutina().dodajSerum("Geek & Gorgeous A-Game 0.05, 30 ml");
	rezultat.getVecernjaRutina().dodajAktivnuSupstancu("Retinol");
	update(rezultat);
end

rule "Bore - premium budžet (jutarnja rutina, vec koriscen vitamin c)"
salience 82
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.PREMIUM, korisceniSastojci contains Sastojak.VITAMIN_C)
    rezultat: SkincareResult(kategorijaNege contains "AntiAge", jutarnjaRutina.aktivneSupstance excludes "Vitamin C")
then
	rezultat.getJutarnjaRutina().dodajSerum("Paula's Choice C25 Super Booster, 15 ml");
	rezultat.getJutarnjaRutina().dodajAktivnuSupstancu("Vitamin C");
	update(rezultat);
end

rule "Bore - premium budžet (jutarnja rutina, nije koriscen vitamin c)"
salience 82
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.PREMIUM, korisceniSastojci excludes Sastojak.VITAMIN_C)
    rezultat: SkincareResult(kategorijaNege contains "AntiAge", jutarnjaRutina.aktivneSupstance excludes "Vitamin C")
then
	rezultat.getJutarnjaRutina().dodajSerum("Paula's Choice C15 Super Booster, 20 ml");
	rezultat.getJutarnjaRutina().dodajAktivnuSupstancu("Vitamin C");
	update(rezultat);
end

rule "Bore - premium budžet (vecernja rutina, vec koriscen retinol)"
salience 82
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.PREMIUM, korisceniSastojci contains Sastojak.RETINOL)
    rezultat: SkincareResult(kategorijaNege contains "AntiAge", vecernjaRutina.aktivneSupstance excludes "Retinol")
then
	rezultat.getVecernjaRutina().dodajSerum("Paula's Choice 1% Retinol Treatment, 30 ml");
	rezultat.getVecernjaRutina().dodajAktivnuSupstancu("Retinol");
	update(rezultat);
end

rule "Bore - premium budžet (vecernja rutina, nije koriscen retinol)"
salience 82
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.PREMIUM, korisceniSastojci excludes Sastojak.RETINOL)
    rezultat: SkincareResult(kategorijaNege contains "AntiAge", vecernjaRutina.aktivneSupstance excludes "Retinol")
then
	rezultat.getVecernjaRutina().dodajSerum("Paula's Choice 0.3% Retinol + 2% Bakuchiol Treatment, 30 ml");
	rezultat.getVecernjaRutina().dodajAktivnuSupstancu("Retinol");
	update(rezultat);
end

rule "Fleke - ekonomičan budžet (jutarnja rutina, vec koriscen vitamin c)"
salience 85
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.EKONOMICAN, korisceniSastojci contains Sastojak.VITAMIN_C)
    rezultat: SkincareResult(kategorijaNege contains "Pigmentacija", jutarnjaRutina.aktivneSupstance excludes "Vitamin C")
then
	rezultat.getJutarnjaRutina().dodajSerum("Revox B77 Just Vitamin C 20%, 30 ml");
	rezultat.getJutarnjaRutina().dodajAktivnuSupstancu("Vitamin C");
	update(rezultat);
end

rule "Fleke - ekonomičan budžet (jutarnja rutina, nije koriscen vitamin c)"
salience 85
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.EKONOMICAN, korisceniSastojci excludes Sastojak.VITAMIN_C)
    rezultat: SkincareResult(kategorijaNege contains "Pigmentacija", jutarnjaRutina.aktivneSupstance excludes "Vitamin C")
then
	rezultat.getJutarnjaRutina().dodajSerum("Balea VITAMIN C serum za lice, 30 ml");
	rezultat.getJutarnjaRutina().dodajAktivnuSupstancu("Vitamin C");
	update(rezultat);
end

rule "Fleke - ekonomičan budžet (vecernja rutina, vec koriscena glikolna kiselina)"
salience 85
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.EKONOMICAN, korisceniSastojci contains Sastojak.GLIKOLNA_KISELINA)
    rezultat: SkincareResult(kategorijaNege contains "Pigmentacija", vecernjaRutina.aktivneSupstance excludes "Glikolna kiselina")
then
	rezultat.getVecernjaRutina().dodajSerum("Balea Beauty Expert Serum sa 10% glikolne kiseline, 30 ml");
	rezultat.getVecernjaRutina().dodajAktivnuSupstancu("Glikolna kiselina");
	update(rezultat);
end

rule "Fleke - ekonomičan budžet (vecernja rutina, nije koriscena glikolna kiselina)"
salience 85
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.EKONOMICAN, korisceniSastojci excludes Sastojak.GLIKOLNA_KISELINA)
    rezultat: SkincareResult(kategorijaNege contains "Pigmentacija", vecernjaRutina.aktivneSupstance excludes "Glikolna kiselina")
then
	rezultat.getVecernjaRutina().dodajSerum("Balea Beauty Expert 5% Glycolic Acid Tonik, 125 ml");
	rezultat.getVecernjaRutina().dodajAktivnuSupstancu("Glikolna kiselina");
	update(rezultat);
end

rule "Fleke - srednji budžet (jutarnja rutina, vec koriscen vitamin c)"
salience 85
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.SREDNJI, korisceniSastojci contains Sastojak.VITAMIN_C)
    rezultat: SkincareResult(kategorijaNege contains "Pigmentacija", jutarnjaRutina.aktivneSupstance excludes "Vitamin C")
then
	rezultat.getJutarnjaRutina().dodajSerum("Geek & Gorgeous C-Glow, 30 ml");
	rezultat.getJutarnjaRutina().dodajAktivnuSupstancu("Vitamin C");
	update(rezultat);
end

rule "Fleke - srednji budžet (jutarnja rutina, nije koriscen vitamin c)"
salience 85
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.SREDNJI, korisceniSastojci excludes Sastojak.VITAMIN_C)
    rezultat: SkincareResult(kategorijaNege contains "Pigmentacija", jutarnjaRutina.aktivneSupstance excludes "Vitamin C")
then
	rezultat.getJutarnjaRutina().dodajSerum("Q+A Vitamin C Brightening Serum, 30 ml");
	rezultat.getJutarnjaRutina().dodajAktivnuSupstancu("Vitamin C");
	update(rezultat);
end

rule "Fleke - srednji budžet (vecernja rutina, vec koriscena glikolna kiselina)"
salience 85
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.SREDNJI, korisceniSastojci contains Sastojak.GLIKOLNA_KISELINA)
    rezultat: SkincareResult(kategorijaNege contains "Pigmentacija", vecernjaRutina.aktivneSupstance excludes "Glikolna kiselina")
then
	rezultat.getVecernjaRutina().dodajSerum("Bielenda Professional Exfoliating Face Serum with 10% Glycolic Acid, 30 ml");
	rezultat.getVecernjaRutina().dodajAktivnuSupstancu("Glikolna kiselina");
	update(rezultat);
end

rule "Fleke - srednji budžet (vecernja rutina, nije koriscena glikolna kiselina)"
salience 85
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.SREDNJI, korisceniSastojci excludes Sastojak.GLIKOLNA_KISELINA)
    rezultat: SkincareResult(kategorijaNege contains "Pigmentacija", vecernjaRutina.aktivneSupstance excludes "Glikolna kiselina")
then
	rezultat.getVecernjaRutina().dodajSerum("The Ordinary Glycolic Acid 7% Toning Solution, 30 ml");
	rezultat.getVecernjaRutina().dodajAktivnuSupstancu("Glikolna kiselina");
	update(rezultat);
end

rule "Fleke - premium budžet (jutarnja rutina, vec koriscen vitamin c)"
salience 85
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.PREMIUM, korisceniSastojci contains Sastojak.VITAMIN_C)
    rezultat: SkincareResult(kategorijaNege contains "Pigmentacija", jutarnjaRutina.aktivneSupstance excludes "Vitamin C")
then
	rezultat.getJutarnjaRutina().dodajSerum("Paula's Choice C25 Super Booster, 15 ml");
	rezultat.getJutarnjaRutina().dodajAktivnuSupstancu("Vitamin C");
	update(rezultat);
end

rule "Fleke - premium budžet (jutarnja rutina, nije koriscen vitamin c)"
salience 85
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.PREMIUM, korisceniSastojci excludes Sastojak.VITAMIN_C)
    rezultat: SkincareResult(kategorijaNege contains "Pigmentacija", jutarnjaRutina.aktivneSupstance excludes "Vitamin C")
then
	rezultat.getJutarnjaRutina().dodajSerum("Paula's Choice C15 Super Booster, 20 ml");
	rezultat.getJutarnjaRutina().dodajAktivnuSupstancu("Vitamin C");
	update(rezultat);
end

rule "Fleke - premium budžet (vecernja rutina, vec koriscena glikolna kiselina)"
salience 85
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.PREMIUM, korisceniSastojci contains Sastojak.GLIKOLNA_KISELINA)
    rezultat: SkincareResult(kategorijaNege contains "Pigmentacija", vecernjaRutina.aktivneSupstance excludes "Glikolna kiselina")
then
	rezultat.getVecernjaRutina().dodajSerum("Drunk Elephant T.L.C. Framboos Glycolic Night Serum, 30 ml");
	rezultat.getVecernjaRutina().dodajAktivnuSupstancu("Glikolna kiselina");
	update(rezultat);
end

rule "Fleke - premium budžet (vecernja rutina, nije koriscena glikolna kiselina)"
salience 85
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.PREMIUM, korisceniSastojci excludes Sastojak.GLIKOLNA_KISELINA)
    rezultat: SkincareResult(kategorijaNege contains "Pigmentacija", vecernjaRutina.aktivneSupstance excludes "Glikolna kiselina")
then
	rezultat.getVecernjaRutina().dodajSerum("Paula's Choice Skin Perfecting 8% AHA Gel Exfoliant, 30 ml");
	rezultat.getVecernjaRutina().dodajAktivnuSupstancu("Glikolna kiselina");
	update(rezultat);
end

rule "Nijedan - ekonomičan budžet (jutarnja rutina)"
salience 85
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.EKONOMICAN)
	rezultat: SkincareResult(kategorijaNege contains "Odrzavanje", jutarnjaRutina.serum == null)
then
	rezultat.getJutarnjaRutina().dodajSerum("Balea Beauty Hyaluron Serum za lice, 30 ml");
	update(rezultat);
end

rule "Nijedan - ekonomičan budžet (vecernja rutina, vec korisceni ceramidi)"
salience 85
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.EKONOMICAN, korisceniSastojci contains Sastojak.CERAMIDI)
	rezultat: SkincareResult(kategorijaNege contains "Odrzavanje", vecernjaRutina.aktivneSupstance excludes "Ceramidi")
then
	rezultat.getVecernjaRutina().dodajSerum("Balea Beauty Expert Umirujući serum za lice, 30 ml");
	rezultat.getVecernjaRutina().dodajAktivnuSupstancu("Ceramidi");
	update(rezultat);
end

rule "Nijedan - ekonomičan budžet (vecernja rutina, nisu korisceni ceramidi)"
salience 85
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.EKONOMICAN, korisceniSastojci excludes Sastojak.CERAMIDI)
	rezultat: SkincareResult(kategorijaNege contains "Odrzavanje", vecernjaRutina.aktivneSupstance excludes "Ceramidi")
then
	rezultat.getVecernjaRutina().dodajSerum("Balea Natural Beauty Serum za lice, 30 ml");
	rezultat.getVecernjaRutina().dodajAktivnuSupstancu("Ceramidi");
	update(rezultat);
end

rule "Nijedan - srednji budžet (jutarnja rutina)"
salience 85
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.SREDNJI)
	rezultat: SkincareResult(kategorijaNege contains "Odrzavanje", jutarnjaRutina.serum == null)
then
	rezultat.getJutarnjaRutina().dodajSerum("The Ordinary Hyaluronic Acid 2% + B5, 30 ml");
	update(rezultat);
end

rule "Nijedan - srednji budžet (vecernja rutina, vec korisceni ceramidi)"
salience 85
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.SREDNJI, korisceniSastojci contains Sastojak.CERAMIDI)
	rezultat: SkincareResult(kategorijaNege contains "Odrzavanje", vecernjaRutina.aktivneSupstance excludes "Ceramidi")
then
	rezultat.getVecernjaRutina().dodajSerum("The Ordinary Soothing & Barrier Support Serum, 30 ml");
	rezultat.getVecernjaRutina().dodajAktivnuSupstancu("Ceramidi");
	update(rezultat);
end

rule "Nijedan - srednji budžet (vecernja rutina, nisu korisceni ceramidi)"
salience 85
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.SREDNJI, korisceniSastojci excludes Sastojak.CERAMIDI)
	rezultat: SkincareResult(kategorijaNege contains "Odrzavanje", vecernjaRutina.aktivneSupstance excludes "Ceramidi")
then
	rezultat.getVecernjaRutina().dodajSerum("Q+A Ceramide Barrier Defense Face Serum, 50 ml");
	rezultat.getVecernjaRutina().dodajAktivnuSupstancu("Ceramidi");
	update(rezultat);
end

rule "Nijedan - premium budžet (jutarnja rutina)"
salience 85
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.PREMIUM)
	rezultat: SkincareResult(kategorijaNege contains "Odrzavanje", jutarnjaRutina.serum == null)
then
	rezultat.getJutarnjaRutina().dodajSerum("Vichy Mineral 89 Fortifying and Plumping Daily Booster, 50 ml");
	update(rezultat);
end

rule "Nijedan - premium budžet (vecernja rutina, vec korisceni ceramidi)"
salience 85
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.PREMIUM, korisceniSastojci contains Sastojak.CERAMIDI)
	rezultat: SkincareResult(kategorijaNege contains "Odrzavanje", vecernjaRutina.aktivneSupstance excludes "Ceramidi")
then
	rezultat.getVecernjaRutina().dodajSerum("Paula's Choice Omega+ Complex Serum, 30 ml");
	rezultat.getVecernjaRutina().dodajAktivnuSupstancu("Ceramidi");
	update(rezultat);
end

rule "Nijedan - premium budžet (vecernja rutina, nisu korisceni ceramidi)"
salience 85
no-loop true
when
	zahtev: SkincareRequest(budzet == Budzet.PREMIUM, korisceniSastojci excludes Sastojak.CERAMIDI)
	rezultat: SkincareResult(kategorijaNege contains "Odrzavanje", vecernjaRutina.aktivneSupstance excludes "Ceramidi")
then
	rezultat.getVecernjaRutina().dodajSerum("Kiehl's Vital Skin-Strengthening Super Serum, 30 ml");
	rezultat.getVecernjaRutina().dodajAktivnuSupstancu("Ceramidi");
	update(rezultat);
end